name: Publish UPM Package

on:
  release:
    types: [published]

jobs:
  bump-up-version:

    runs-on: ubuntu-latest

    env:
      REPOSITORY: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    steps:
    - uses: actions/checkout@v2
    - name: Install required commands
      run: |
        sudo apt-get update && sudo apt-get install jq
    - name: Replace package.json and CHANGELOG.md
      run: |
        version="${{ github.event.release.tag_name }}"
        summary="${{ github.event.release.name }}"
        body="${{ github.event.release.body }}"
        cat << EOS | sed -i '1r /dev/stdin' Assets/CHANGELOG.md
        
        ## [${version##v}] - $(date "+%Y-%m-%d")
        
        ${summary}
        
        $(echo "${body}" | sed 's/^#/\#\#/')
        EOS
        cat Assets/package.json | jq -Mr '. | .version = "'"${version##v}"'"' > Assets/package.json
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m ":up: Bump up version: ${version}" && git push ${REPOSITORY} HEAD:${{ github.event.release.target_commitish }} || true
