name: Publish UPM Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required commands
      run: |
        sudo apt-get update && sudo apt-get install jq
    - name: Show Release Body
      run: |
        version=${{ github.event.release.tag_name }}
        summary=${{ github.event.release.name }}
        body=${{ github.event.release.body }}
        cat << EOS | sed -i '1r /dev/stdin' Assets/CHANGELOG.md
        
        ## [${version##v}] - $(date "+%Y-%m-%d")
        
        ${summary}
        
        $(echo ${body} | sed 's/^#/\#\#/')
        EOS
        cat Assets/CHANGELOG.md
