name: Publish UPM Package

on:
  release:
    types: [published]

jobs:
  bump-up-version:

    runs-on: ubuntu-latest

    if: secrets.NPM_AUTH_TOKEN != ''

    env:
      REPOSITORY: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      VERSION: ${{ github.event.release.tag_name }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: monry/actions-upm-publish@develop
